.TH PF_getUns 3GF
.UC 4
.SH NAME
PF_getUns\- Convert a String to an Unsigned Integer with range checking.
.br
PF_getInt, PF_getLgInt.
.SH SYNOPSIS
.B #include "pf.h"
.PP
.B Int PF_getUns(str, result, def, min, max)
.nf
String *str;    /* pointer to the string in question */
Uns *result;    /* out */ 
Uns def;        /* the default value */
Uns min;        /* minimum acceptable value */
Uns max;        /* maximum acceptable value */
.fi
.SH DESCRIPTION
.PP
PF_getUns converts a String into an integer.
(*result) contains  the value represented by the String.
If  str is NULL or unacceptable, def is assigned to (*result).
Str should represent an integer that is in the range min to max.
.PP
Return value of PF_getUns is:
.nf

      0 - If every thing went fine.
      1 - If there had been an invalid entry
      2 - If the entry was not with in the specified range
.fi
