/*
 *  Copyright (C) 1995,1996  Neda Communications, Inc. All rights reserved.
 * 
 *  This software is furnished under a license and use, duplication,
 *  disclosure and all other uses are restricted to the rights specified
 *  in the written license between the licensee and copyright holders.
 * 
 */

/*+
 * These functions are not going to be supported in future.
 *
 *
-*/

/*
 * Author: Mohsen Banan.
 * History:
 *
 */

#ifdef RCS_VER	/*{*/
static char rcs[] = "$Id: compat.c,v 1.1.1.1 1998/01/30 00:50:06 mohsen Exp $";
#endif /*}*/


/* 
 * This file is automatically generated.  Do not edit. 
 */

#include "estd.h"
#include "pf.h"
#include "eh.h"
#include "relid.h"
#include "cpr.h"

/* 
 * the Copyright notice.
 */

static Char combinedString[512]= {0};



PUBLIC String 
RELID_getCopyrightNeda(Void)
{
  Char *index;
  String str;

  if ( ! (str=RELID_getRelidNotice()) ) {
    return ( (String) 0 );
  }
   
  index = PF_strmcpy(&combinedString[0],
		     str,
		     ENDOF(combinedString));

  if ( ! (str=CPR_getCopyrightNeda()) ) {
    return ( (String) 0 );
  }

  index = PF_strmcpy(index,
		     str,
		     ENDOF(combinedString));

  return ( combinedString );

}

PUBLIC String 
RELID_getCopyrightNedaAtt(Void)
{
  Char *index;
  String str;

  if (! (str=RELID_getRelidNotice()) ) {
    return ( (String) 0 );
  }
   
  index = PF_strmcpy(&combinedString[0],
		     str,
		     ENDOF(combinedString));


  if ( ! (str=CPR_getCopyrightNedaAtt()) ) {
    return ( (String) 0 );
  }

  index = PF_strmcpy(index,
		     str,
		     ENDOF(combinedString));

  return ( combinedString );
}

PUBLIC String 
RELID_getCopyrightAtt(Void)
{

  Char *index;
  String str;

  if ( ! (str=RELID_getRelidNotice()) ) {
    return ( (String) 0 );
  }
   
  index = PF_strmcpy(&combinedString[0],
		     str,
		     ENDOF(combinedString));

  if ( ! (str=CPR_getCopyrightAtt()) ) {
    return ( (String) 0 );
  }

  index = PF_strmcpy(index,
		     str,
		     ENDOF(combinedString));

  return ( combinedString );
}

